blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('jobs.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from datetime import datetime


class MyBlog(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    body = models.TextField()
    pub_date = models.DateField(default=datetime.now, blank=True)

    def summary(self):
        return self.body[:100] + "..."

    def __str__(self):
        return self.title

jobs/models.py
from django.db import models


class Job(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    summary = models.CharField(max_length=200)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import MyBlog


def blog(request):
    blogs = MyBlog.objects.all()

    return render(request, 'blog/allblogs.html', {'blogs': blogs})


def detail(request, blog_id):
    detailblog = get_object_or_404(MyBlog, pk=blog_id)

    return render(request, 'blog/detailblog.html', {'detailblog': detailblog})

jobs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from .models import Job


def index(request):
    jobs = Job.objects.all()

    return render(request, 'jobs/index.html', {'jobs': jobs})

templates/blog/allblogs.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">
        <title>John's Blog</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


        <style>
        .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
        }

        @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                        font-size: 3.5rem;
                }
        }
        </style>
        <!-- Custom styles for this template -->
        <link href="album.css" rel="stylesheet">
</head>
<body>
        <header>
                <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark mb-5">
                        <a class="navbar-brand" href="{% url 'jobs:index' %}">John Tovor</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                <div class="navbar-nav ml-auto">
                                        <a class="nav-item nav-link " href="https://twitter.com/jmarvenn" target="_blank">Twitter</a>
                                        <a class="nav-item nav-link" href="https://www.linkedin.com/in/johntovor" target="_blank">LinkedIn</a>
                                        <a class="nav-item nav-link" href="{% static 'images/john_cv.docx' %}">Resume</a>
                                        <a class="nav-item nav-link" href="{% url 'blog:all_blogs' %}" >Blog</a>
                                </div>
                        </div>
                </nav>
        </header>

        <main role="main">
                <div class="container">
                        <h1 class="text-center py-4 mt-5">Welcome to John's Blog</h1>
                        <h2>Latest Posts</h2>
                        <hr>
                </div>

                <div class="album py-5 bg-light">
                        <div class="container">

                                <div class="row">
                                        {% for blog in blogs %}
                                        <div class="col-md-4">
                                                <div class="card mb-4 shadow-sm">
                                                        <div class="card-title text-center pt-3 mb-0">
                                                                {{ blog.title }}
                                                        </div>
                                                        <hr>
                                                        <img class="card-img-top" src="{{ blog.image.url }}" alt="" width="200" height="200">
                                                        <div class="card-body">
                                                                <p class="card-text">{{ blog.summary }}</p>
                                                                <hr>
                                                                <p class="card-text">Posted On: {{ blog.pub_date }}</p>

                                                                <a href="{% url 'blog:detail' blog.id %}" class="btn btn-primary btn-block">Read Full Post</a>
                                                        </div>
                                                </div>
                                        </div>
                                        {% endfor %}

                                </div>
                        </div>
                </div>
        </main>

        <footer class="text-muted">
                <div class="container text-center">
                        <p>Copyright John Tovor, {% now 'Y' %}</p>
                </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

templates/blog/detailblog.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">
        <title>{{ detailblog.title }}</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


        <style>
        .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
        }

        @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                        font-size: 3.5rem;
                }
        }
        </style>
        <!-- Custom styles for this template -->
        <link href="album.css" rel="stylesheet">
</head>
<body>
        <header>
                <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark mb-3">
                        <a class="navbar-brand" href="{% url 'jobs:index' %}">John Tovor</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                <div class="navbar-nav ml-auto">
                                        <a class="nav-item nav-link " href="https://twitter.com/jmarvenn" target="_blank">Twitter</a>
                                        <a class="nav-item nav-link" href="https://www.linkedin.com/in/johntovor" target="_blank">LinkedIn</a>
                                        <a class="nav-item nav-link" href="{% static 'images/john_cv.docx' %}">Resume</a>
                                        <a class="nav-item nav-link" href="{% url 'blog:all_blogs' %}" >Blog</a>
                                </div>
                        </div>
                </nav>
        </header>

        <main role="main">
                <div class="album py-5 bg-light">
                        <div class="container">

                                <div class="row">
                                        <div class="col-12">
                                                <div class="card mb-4 shadow-sm mt-5">
                                                        <div class="card-title text-center pt-3 mb-0">
                                                                {{ detailblog.title }}
                                                        </div>
                                                        <hr>
                                                        <img class="card-img-top" src="{{ detailblog.image.url }}" alt="" width="200" height="500">
                                                        <div class="card-body">
                                                                <p class="card-text">{{ detailblog.body }}</p>
                                                                <hr>
                                                                <p class="card-text">Posted On: {{ detailblog.pub_date }}</p>
                                                        </div>
                                                </div>
                                        </div>

                                </div>
                        </div>
                </div>
        </main>

        <footer class="text-muted">
                <div class="container text-center">
                        <p>Copyright John Tovor, {% now 'Y' %}</p>
                </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

templates/jobs/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Jekyll v3.8.5">
        <title>John Tovor</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/album/">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


        <style>
        .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                -ms-user-select: none;
                user-select: none;
        }

        @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                        font-size: 3.5rem;
                }
        }
        </style>
        <!-- Custom styles for this template -->
        <link href="album.css" rel="stylesheet">
</head>
<body>
        <header>
                <nav class="navbar  fixed-top navbar-expand-lg navbar-dark bg-dark">
                        <a class="navbar-brand" href="{% url 'jobs:index' %}">John Tovor</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                                <div class="navbar-nav ml-auto">
                                        <a class="nav-item nav-link " href="https://twitter.com/jmarvenn" target="_blank">Twitter</a>
                                        <a class="nav-item nav-link" href="https://www.linkedin.com/in/johntovor" target="_blank">LinkedIn</a>
                                        <a class="nav-item nav-link" href="{% static 'images/john_cv.docx' %}">Resume</a>
                                        <a class="nav-item nav-link" href="{% url 'blog:all_blogs' %}" >Blog</a>
                                </div>
                        </div>
                </nav>
        </header>

        <main role="main">

                <section class="jumbotron text-center">
                        <div class="container">
                                <h1 class="jumbotron-heading">Creator, Inventor, Entrepreneur, Forerunner!</h1>
                                <p class="lead text-muted">I am endowed with a lot of abilities to create and reinvent the future. <br> The future of Artificial Intelligence and Machine Learning is my greatest obssession!</p>
                                <p>
                                        <a href="mailto:johntovor@gmail.com" class="btn btn-primary my-2">Contact Me!</a>
                                </p>

                                <img class="img-fluid img-thumbnail" src="{% static 'images/john.jpg' %}" alt="" height="350" width="350">
                        </div>
                </section>

                <div class="album py-5 bg-light">
                        <div class="container">

                                <div class="row">
                                        {% for job in jobs %}
                                        <div class="col-md-4">
                                                <div class="card mb-4 shadow-sm">
                                                        <div class="card-title text-center pt-3 mb-0">
                                                                {{ job.title }}
                                                        </div>
                                                        <hr>
                                                        <img class="card-img-top" src="{{ job.image.url }}" alt="" height="200" width="200">
                                                        <div class="card-body">
                                                                <p class="card-text">{{ job.summary }}</p>
                                                                <div class="d-flex justify-content-center align-items-center">
                                                                        <div>
                                                                                <a href="" class="btn btn-success btn-block">View</a>
                                                                        </div>

                                                                </div>
                                                        </div>
                                                </div>
                                        </div>
                                        {% endfor %}

                                </div>
                        </div>
                </div>

        </main>

        <footer class="text-muted">
                <div class="container text-center">
                        <p>Copyright John Tovor, {% now 'Y' %}</p>
                </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>